- .gitignore
- requirements.txt
- tests/utils/test_perf_monitor.py
- utils/perf_monitor.py
Adding a little util to track performance of a block of code. This'll be useful for tracking how long various operations take, such as downloading models, computing losses, etc.
> Add a class to monitor performance of a block of code

- neurons/miner.py
- pretrain/mining.py
With these changes, I was able to:
1. Train a model from scratch and upload it to the chain + hugging face
2. Train from the best existing model (which only has the model.safetensor file from wandb)
3. Start a new training run from the model saved from step 2 above
> Adds support to train from an existing model.safetensor file

- constants/__init__.py
- model/model_updater.py
- model/storage/chain/chain_model_metadata_store.py
- model/storage/hugging_face/hugging_face_model_store.py
- model/storage/hugging_face/test_hugging_face_model_store.py
- neurons/miner.py
- neurons/validator.py
- pretrain/__init__.py
- pretrain/graph.py
- pretrain/mining.py
- pretrain/validation.py
- tools/clean_runs.py
- tools/eval_all.py
- tools/upload_model.py
1. Adds a tool to upload a previously trained model. This is useful if the training run crashes
2. Moves constants out of pretrain to avoid circular dependency issues (I also had to split out the test for the hugging face store for the same reason)
> Add a stand-alone tool to push a model from disk

- neurons/validator.py
Also rename the tracker file to force re-download and evaluation for pre-existing validators.
> Fix for pending uids to eval in next loop.

- constants/__init__.py
- neurons/miner.py
- neurons/validator.py
- pretrain/__init__.py
- tests/utilities/test_utils.py
- utilities/utils.py
Add a check to the vali on start to detect a version upgrade.
Also delays the clean-up loop so that the update loop has a chance to perform a full iteration across miners to avoid deleting models from miners that are still registered.
> Perform a full eval after vali upgrade

- neurons/validator.py
- utilities/utils.py
A miner uploaded a model that used a different number of params on the input layer, causing a CUDA error. It seems, once such an error occurs, the GPU is in a bad state and attempts to empty the cache on it don't work. 
Instead we run each eval in a subprocess to ensure the GPU is reset between model evals.
> Run each eval in a subprocess

- neurons/validator.py
If a miner fails to be evaluated, drop it from the set to evaluate next round, even if it's a "top 30" miner by circumstance.
> Remove miners with inf loss

- neurons/validator.py
- tests/utilities/test_utils.py
- utilities/utils.py
On a few occasions, valis have deleted the model store directory to free up space but didn't clean-up the vali-state files. This puts the vali in a bad state. 
In this change, we move the vali-state files inside the model-dir so they have a shared fate.
> Move state file to the model dir

- model/storage/disk/utils.py
- tests/model/storage/disk/test_utils.py
Note that since all files under a specific model folder get written together this will not meaningfully affect any behavior but this is the correct way to calculate it.
> Fix get_newest_datetime_under_path to get newest not oldest.

- constants/__init__.py
- model/model_updater.py
- model/utils.py
- tests/model/test_model_updater.py
- tests/model/test_utils.py
Adds all necessary logic to support models of size 772M as of block 2,405,920.
> Add model parameter limits based on the block they were uploaded

- constants/__init__.py
- neurons/validator.py
- pretrain/validation.py
- scripts/vali-perf.ipynb
- Log when a vali fails to set weights
- Decrease alpha to 0.5 to make vali convergence faster
- Load the model in the subprocess to avoid pickling it
- Decrease the number of models eval'd to 25
> Bucket o' improvements

- .gitignore
- neurons/validator.py
- pretrain/validation.py
Raise threshold for unreasonable output and keep models with weights.
This helps ensure the reasonable model check does not falsely penalize reasonable models.
> Raise threshold for unreasonable output and keep models with weights.

- neurons/validator.py
Although this gets assigned as a set later on, there is an edge case when a fresh vali loads and fails to complete the first eval loop that can cause type mismatches later.
> Initialize uids_to_eval as set().

- docs/miner.md
- neurons/miner.py
- pretrain/mining.py
- scripts/upload_model.py
When the flag is passed, miners will do the final load_local_model call using bfloat16 to reduce the size before uploading to hugging face.
By default, from_pretrained from local files will upsample a bfloat16 model to fp32. This can double the size of the local model which would cause it to fail the validator 15 GB limit check. Note: when downloading this does not seem to occur.
Aside from the size limit, it does not matter how the model gets uploaded.
- Validators will download the model with the exact same code that miners use to generate the repo hash.
- Validators will load a model for inference from disk with bfloat16 and flash attention 2 regardless of what is in the repo.
> Enable uploading a model with bfloat 16.

- neurons/config.py
- neurons/validator.py
- Move the config into its own file to make it easier to find flags for the validator
- Remove code to migrate the old state files, since we're many updates past that code was needed.
> Remove dead code

- constants/__init__.py
- model/data.py
- model/storage/chain/chain_model_metadata_store.py
- neurons/validator.py
- pretrain/dataset.py
- requirements.txt
- tests/model/test_model_utils.py
- tests/pretrain/test_dataset.py
**Context**
The current implementation of the dataset migration evaluates only models submitted after a specified block on the new dataset. This behavior does not align with our intended functionality.
**Goal**
The objective of this PR is to ensure that after the specified migration block, all models, regardless of their submission time, are evaluated on the new dataset. Additionally, once the migration block is reached, the code supporting the old dataset could be completely removed, streamlining the evaluation process.
> Hotfix: Fixed reference block number

- neurons/validator.py
This ensures that when a UID uploads a model to a different competition and is successfully getting weights that we still drop it from set of uids to try on the old competition.
> Use competition specific weights when prioritizing keeps.

- neurons/validator.py
Logs look as follows:
Evaluation:
```
2024-08-18 22:30:35.716 |      DEBUG       | Competition 1 | Computing losses on [71, 140, 148, 154, 94]
2024-08-18 22:30:35.716 |      DEBUG       | Pages used are [821968790, 710143056, 150266581, 787989376, 769501251]
2024-08-18 22:30:35.716 |      TRACE       | Getting metadata for uid: 71.
2024-08-18 22:30:35.716 |       INFO       | Evaluating uid: 71 / hotkey: 5FbHSCqz2Be6zAxEqgEkKvLoJQcjZrqyt2HrTk2V62WnJWYH with metadata: ModelMetadata(id=ModelId(namespace='TdL', name='test_repo', competition_id=1, commit='618fd986e24698eaf1873d300bd35fe66faa7b72', hash=None, secure_hash='qYsS46HVGJ0GDsvF5QDH3zqJuvCUNFSs6BL7YNycF3c='), block=3601787) and hf_url: https://huggingface.co/TdL/test_repo/tree/618fd986e24698eaf1873d300bd35fe66faa7b72.
```
Step Log: …
> Log metadata in eval loop.

- constants/__init__.py
- neurons/validator.py
- requirements.txt
The step log table now correctly wraps rather than eliding text.
```
0|vali  | 2024-08-23 18:24:28.959 |      TRACE       | Computed model losses for uid:209 with average loss: 2.4440023282712158
0|vali  | 2024-08-23 18:24:28.967 |      TRACE       | Saving validator state.
0|vali  |                                       Step
0|vali  | ┏━━━━━┳━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━┓
0|vali  | ┃     ┃        ┃ average ┃ win_ra ┃ win_tot ┃ total_ ┃ comp_w ┃        ┃      ┃
0|vali  | ┃ uid ┃ hf     ┃ _loss   ┃ te     ┃ al      ┃ weight ┃ eight   ┃ block  ┃ comp ┃
0|vali  | ┡━━━━━╇━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━┩
0|vali  | │ 209 │ rwh/me │ 2.444   │ 0      │ 0       │ 1.0    │ 1.0     │ 364637 │ 2    │
0|vali  | │     │ …
```
> Bump pretraining/taoverse versions and improve logging.

- constants/__init__.py
- requirements.txt
This is a necessary precursor to releasing the 14b competition.
NOTE: Not yet fully tested. Waiting for taoverse package update
> Define per-competition maximum model size (in bytes)

- neurons/validator.py
The validator is currently syncing the metagraph in 2 ways:
1. Via the metagraph_syncer
2. Via "try_sync_metagraph"
This change makes it so we only sync via the metagraph_syncer
> Remove duplicated metagraph syncing

- docs/validator.md
- neurons/validator.py
- pretrain/validation.py
Example logs:
```
0|vali  | 2024-08-28 03:58:39.866 |      DEBUG       | Eval: Load model performance: N=2 | Min=1.28 s | Max=7.70 s | Median=4.49 s | P90=7.06 s
0|vali  | 2024-08-28 03:58:39.866 |      DEBUG       | Eval: Compute loss performance: N=2 | Min=1.74 min | Max=1.92 min | Median=1.83 min | P90=1.90 min
0|vali  |                                       Step
0|vali  | ┏━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━┓
0|vali  | ┃     ┃       ┃ avera ┃       ┃       ┃       ┃ total ┃ comp_ ┃       ┃        ┃
0|vali  | ┃     ┃       ┃ ge_lo ┃ epsil ┃ win_r ┃ win_t ┃ _weig ┃ weigh ┃       ┃        ┃
0|vali  | ┃ uid ┃ hf    ┃ ss    ┃ on    ┃ ate   ┃ otal  ┃ ht    ┃ t     ┃ block ┃ comp   ┃
0|vali  | …
```
> Use per competition epsilon func.

- constants/__init__.py
- This PR adds a new model constraints dict with support for `LinearDecay` epsilon. 
- The activation block for the linear decay epsilon is set to the same as the 14B competition.
- The validator schema version is bumped given the latest changes in the validator (Retrying models with more likelihood to win with lower epsilon)
- The model constraints dict with the fixed epsilon will be cleaned up in the next release once the activation block for LinearDecay epsilon has passed.
> Add LinearDecay epsilon to schedule

- constants/__init__.py
- docs/validator.md
- Reverted validator schema version to 3.1.0 since it was unnecessarily bumped in a previous PR
- Updated validator system requirements to require use of A100 with 80GB.
> Updated validator systerm requirements

- constants/__init__.py
- docs/validator.md
- neurons/validator.py
- Includes deactivation block for sunsetting 7B competition (competition ID 0). Block `3849722`.
- The 0.15 reward previously attributed to 7B competition will be added to the 14B competition whose reward will total `0.57`.
- No action to be taken by the validators other than `pip install -e .` of the new release package.
> Release 4.4.0

- constants/__init__.py
- neurons/miner.py
- neurons/validator.py
- pretrain/mining.py
- requirements.txt
This updates to the latest taoverse version which correctly gets the newest instead of the oldest filetime in a directory.
Additionally we bump the grace period to 10 minutes. From testing of downloading the current top 14B model the latest filetime in the directory did update quite frequently, but this should provide additional buffer for those with slower connections.
Checking every 10 seconds during the download we found
```
2024-10-09 23:47:21.027041
2024-10-09 23:47:46.778914
2024-10-09 23:47:46.778914
2024-10-09 23:48:12.698787
2024-10-09 23:48:12.698787
2024-10-09 23:48:12.698787
2024-10-09 23:48:39.022657
2024-10-09 23:48:39.022657
2024-10-09 23:48:59.998554
2024-10-09 23:48:59.998554
2024-10-09 23:48:59.998554
2024-10-09 23:48:59.998554
```
> Fix grace period check for currently downloading models.

- constants/__init__.py
- neurons/validator.py
- Reducing to 11 validation pages instead of 18.
- increasing TTL to 430s instead of 400 (Although all 14B models complete validation under 400s seconds).
- Also reducing decay period to 1 week instead of two for 14B. Two weeks seems to be too long for these small loss changes
> Increased ttl for loss computation

- constants/__init__.py
This will force validators to evaluate previously excluded models due to compute_loss ttl
> Bumped validator version

- constants/__init__.py
- neurons/validator.py
- Bumped validator version to force all validators to reevaluate models that have been excluded with 'inf' loss due to the low compute loss TTL in 4.5.0.
- Decay period for 14B has been temporarily extended from 7 to 10 days, so models that had been excluded get a second chance to get a fair ranking.
> Release 4.5.2

- neurons/validator.py
- pretrain/validation.py
- tests/pretrain/test_validation.py
In the current state, the top model can keep uploading copies to extend their epsilon advantage against newer models. For example:
1, At block 100 a model A is uploaded. It’s the best model and gets all incentive
2, At block 125 a clone of model A (model B) is uploaded. 
3, At block 127 a better model C is uploaded. The C model is better than model A and B ( without considering the time advantage).  In real evaluate time, model C is better than A more than the margin 0.0001. so it win model A.
Due to the upload time B is later, model B hold more time advantage over C (0.005). In this case, B will win C.
In this  scenario, Even B is the worst model, but it win number is same as C.
This fix first filters out all models which can't beat all earlier models at full epsilon decay, before …
> Prevent duplicate uploads from providing an incentive advantage

- constants/__init__.py
- neurons/validator.py
- pretrain/validation.py
- tests/pretrain/test_validation.py
- This fix first filters out all models which can't beat all earlier models at full epsilon decay, before computing win rates (and incentive weights). This will ensure that:
- All clones are filtered out before we compute win rates so clones can no longer provide an artificially high win rate.
- Any models that is not better than the fully-decayed top model  but submitted at a later block is discarded from the evaluation process.
- Validator version bumped to 3.4.0
> Release 4.5.3

- pretrain/dataset.py
- tests/pretrain/test_dataset.py
Note that this has a threshold of duplicate pages rather than a timeout to cut out early rather than waiting a full timeout constantly hitting the same page when the dataset is exhausted.
Realistically we will never hit this given the number of pages we load relative to the size of the fineweb dataset.
> Ensure the loader only fetches unique pages.

- constants/__init__.py
- neurons/validator.py
- pretrain/dataset.py
- requirements.txt
- scripts/upload_model.py
- tests/pretrain/test_dataset.py
- tests/pretrain/test_mining.py
In addition to using the seed, we also need to apply a delay to picking up a model to eval to avoid exploits around training on the exact upcoming dataset.
Since the eval delay applies to the constraints per competition, this pull request also cleans up those definitions in constants to just the most recent one. In doing so it was also discovered that a few places in tests or in mining were using now-deprecated constraints.
> Use a seed based on sync block for data loading.

- docs/miner.md
- pretrain/mining.py
- scripts/upload_model.py
- tests/pretrain/test_mining.py
Note this defaults to False as it would be new behavior. Can default to True in the future.
Flag is ```--update_repo_visibility``` which can be passed to the upload_model script.
> Add argument to make repo public after model upload.

- competitions/data.py
- constants/__init__.py
- neurons/config.py
- neurons/validator.py
- pretrain/dataset.py
- requirements.txt
- tests/pretrain/test_dataset.py
Adds a new 14B* competition.
This competition takes the existing evaluation from 14B and adds 5% tokens from The Stack V1 dedup as a secondary dataset using the same competition constraints. The usual loss comparison is done on the combined dataset and the winners for 14B* are captured separately.
Note this requires updating taoverse package and also clearing validator state.
Other changes:
- changed number of rows per page to 50 in the data loading classes for more flexibility in adjusting data mixes.
- Increased lower epsilon bound to 0.0005, and decrease interval to 7 days for 14B.
- Bumped version to 4.6.0
> Added multi-dataset 14B competition

- requirements.txt
Use `smart-open[s3]` instead of `smart-open` in requirements
> Added s3 extra to smart-open install requirement

- neurons/validator.py
1) Adjust set weight retry from 1 to 2 minutes.
2) Wait 3 minutes on websocket.exceptions.InvalidStatus during the update loop to handle 429 or other errors.
> Send subtensor requests less agressively.

- constants/__init__.py
- neurons/validator.py
- pretrain/dataset.py
- pretrain/datasets/factory.py
- pretrain/datasets/ids.py
- pretrain/eval/method.py
- pretrain/eval/sample.py
- pretrain/validation.py
- requirements.txt
Changes
1) Clean up the competition schedule to align on the current competitions / constraints.
2) Add support for EvalTasks in the form of a Dataset Factory + Eval Method refactor.
3) Introduce using EvalTasks for all current competitions in a no-op for outcome.
4) Clean up some more defaults around sample unpacking.
Note2: There is also a small hack to continue supporting the old logging format for losses based on dataset names rather than eval tasks. A comparison can be found in the wandb summary for a run with the old code: https://wandb.ai/macrocosmos/pretraining-validators/runs/4xxftjfh/overview vs the new code: https://wandb.ai/macrocosmos/pretraining-validators/runs/ukgfq6kv/overview.
This also added a lot more detailed per uid per eval task summary metrics.
> Introduce support for multi-dataset competitions.

- pretrain/dataset.py
Our vali has hung in the eval thread a few times in the latest release. The last log line in that thread is
`|  DEBUG  | Seed used for loading data is: XXX.`. This suggests that the DatasetLoader is hanging.
Today,  the dataset loader's requests are not setting a timeout, which could explain the hangs.
> Set timeouts on all calls to request.get()

- constants/__init__.py
- pretrain/graph.py
- pretrain/mining.py
- requirements.txt
the `uid` argument has been missing from some calls to `retrieve_model_metadata` across the codebase. Now fixed!
> Fixed model pushing

- constants/__init__.py
- neurons/validator.py
- Used a fallback seed different from None in the validator. A None fallback seed, when a seed sync fail, causes the TTS model denoisers to lose sync when evaluating different submissions with the same mode. This harms vTrust.
> Used a fallback seed different from None
